### ISSUE TITLE
Undefined class constant 'PDO::FETCH_DEFAULT'

### ISSUE THREAD

**Issue by equisde** [envms/fluentpdo#326]
i've been trying out FluentPDO but when trying to do a query i get

```
[04-Jan-2022 06:46:12 Europe/Amsterdam] PHP Fatal error:  Uncaught Error: Undefined class constant 'PDO::FETCH_DEFAULT' in /home/tunlxzow/systematic.wtf/vendor/envms/fluentpdo/src/Query.php:81
Stack trace:
#0 signup.php(75): Envms\FluentPDO\Query->from('keys')
#1 {main}
  thrown in /vendor/envms/fluentpdo/src/Query.php on line 81
```
what can i do to fix it?
i'm using PHP 7.3

**Comment by equisde** [comment]
i've tried switching php versions but it didn't work  also i've tried deleting PDO::FETCH_DEFAULT from Base.php but now i'm getting

```
[04-Jan-2022 07:11:00 Europe/Amsterdam] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'keys.* FROM keys WHERE key = 'asd'' at line 1 in vendor/envms/fluentpdo/src/Queries/Base.php:507
Stack trace:
#0 vendor/envms/fluentpdo/src/Queries/Base.php(507): PDOStatement->execute()
#1 vendor/envms/fluentpdo/src/Queries/Base.php(202): Envms\FluentPDO\Queries\Base->executeQuery()
#2 vendor/envms/fluentpdo/src/Queries/Select.php(116): Envms\FluentPDO\Queries\Base->execute()
#3 signup.php(75): Envms\FluentPDO\Queries\Select->fetch()
#4 {main}
  thrown in vendor/envms/fluentpdo/src/Queries/Base.php on line 507
```
